name: Release
on:
  workflow_run:
    workflows: ["ci"]
    branches: [main]
    types:
      - completed
  push:
    branches: [main]
    tags: ["*"]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
      - run: sbt ci-release
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
